<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SupportClassSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('support_classes')->insert([
            [
                'name' => 'ウォーリア',
                'strength_correction' => 1,
                'dexterity_correction' => 1,
                'agility_correction' => 1,
                'intelligence_correction' => 0,
                'sense_correction' => 0,
                'mental_correction' => 0,
                'luck_correction' => 0,
                'hp_correction' => 13,
                'mp_correction' => 10,
            ],
            [
                'name' => 'アコライト',
                'strength_correction' => 0,
                'dexterity_correction' => 1,
                'agility_correction' => 0,
                'intelligence_correction' => 1,
                'sense_correction' => 0,
                'mental_correction' => 1,
                'luck_correction' => 0,
                'hp_correction' => 11,
                'mp_correction' => 12,
            ],
            [
                'name' => 'メイジ',
                'strength_correction' => 0,
                'dexterity_correction' => 0,
                'agility_correction' => 0,
                'intelligence_correction' => 1,
                'sense_correction' => 1,
                'mental_correction' => 1,
                'luck_correction' => 0,
                'hp_correction' => 10,
                'mp_correction' => 13,
            ],
            [
                'name' => 'シーフ',
                'strength_correction' => 0,
                'dexterity_correction' => 1,
                'agility_correction' => 1,
                'intelligence_correction' => 0,
                'sense_correction' => 1,
                'mental_correction' => 0,
                'luck_correction' => 0,
                'hp_correction' => 12,
                'mp_correction' => 11,
            ],
            [
                'name' => 'アルケミスト',
                'strength_correction' => 0,
                'dexterity_correction' => 1,
                'agility_correction' => 0,
                'intelligence_correction' => 1,
                'sense_correction' => 1,
                'mental_correction' => 0,
                'luck_correction' => 0,
                'hp_correction' => 10,
                'mp_correction' => 13,
            ],
            [
                'name' => 'イリュージョニスト',
                'strength_correction' => 0,
                'dexterity_correction' => 0,
                'agility_correction' => 0,
                'intelligence_correction' => 1,
                'sense_correction' => 0,
                'mental_correction' => 1,
                'luck_correction' => 1,
                'hp_correction' => 10,
                'mp_correction' => 13,
            ],
            [
                'name' => 'ガンスリンガー',
                'strength_correction' => 0,
                'dexterity_correction' => 1,
                'agility_correction' => 0,
                'intelligence_correction' => 0,
                'sense_correction' => 1,
                'mental_correction' => 1,
                'luck_correction' => 0,
                'hp_correction' => 12,
                'mp_correction' => 11,
            ],
            [
                'name' => 'サムライ',
                'strength_correction' => 1,
                'dexterity_correction' => 1,
                'agility_correction' => 0,
                'intelligence_correction' => 0,
                'sense_correction' => 0,
                'mental_correction' => 1,
                'luck_correction' => 0,
                'hp_correction' => 12,
                'mp_correction' => 11,
            ],
            [
                'name' => 'サモナー',
                'strength_correction' => 0,
                'dexterity_correction' => 0,
                'agility_correction' => 0,
                'intelligence_correction' => 1,
                'sense_correction' => 0,
                'mental_correction' => 1,
                'luck_correction' => 1,
                'hp_correction' => 8,
                'mp_correction' => 15,
            ],
            [
                'name' => 'セージ',
                'strength_correction' => 0,
                'dexterity_correction' => 0,
                'agility_correction' => 0,
                'intelligence_correction' => 1,
                'sense_correction' => 1,
                'mental_correction' => 0,
                'luck_correction' => 1,
                'hp_correction' => 9,
                'mp_correction' => 14,
            ],
            [
                'name' => 'ダンサー',
                'strength_correction' => 0,
                'dexterity_correction' => 0,
                'agility_correction' => 1,
                'intelligence_correction' => 0,
                'sense_correction' => 0,
                'mental_correction' => 1,
                'luck_correction' => 1,
                'hp_correction' => 11,
                'mp_correction' => 12,
            ],
            [
                'name' => 'ニンジャ',
                'strength_correction' => 0,
                'dexterity_correction' => 1,
                'agility_correction' => 1,
                'intelligence_correction' => 1,
                'sense_correction' => 0,
                'mental_correction' => 0,
                'luck_correction' => 0,
                'hp_correction' => 10,
                'mp_correction' => 13,
            ],
            [
                'name' => 'バーサーカー',
                'strength_correction' => 1,
                'dexterity_correction' => 1,
                'agility_correction' => 0,
                'intelligence_correction' => 0,
                'sense_correction' => 1,
                'mental_correction' => 0,
                'luck_correction' => 0,
                'hp_correction' => 13,
                'mp_correction' => 10,
            ],
            [
                'name' => 'バード',
                'strength_correction' => 0,
                'dexterity_correction' => 0,
                'agility_correction' => 0,
                'intelligence_correction' => 0,
                'sense_correction' => 1,
                'mental_correction' => 1,
                'luck_correction' => 1,
                'hp_correction' => 10,
                'mp_correction' => 13,
            ],
            [
                'name' => 'モンク',
                'strength_correction' => 1,
                'dexterity_correction' => 0,
                'agility_correction' => 1,
                'intelligence_correction' => 0,
                'sense_correction' => 0,
                'mental_correction' => 1,
                'luck_correction' => 0,
                'hp_correction' => 12,
                'mp_correction' => 11,
            ],
            [
                'name' => 'レンジャー',
                'strength_correction' => 1,
                'dexterity_correction' => 1,
                'agility_correction' => 0,
                'intelligence_correction' => 0,
                'sense_correction' => 1,
                'mental_correction' => 0,
                'luck_correction' => 0,
                'hp_correction' => 12,
                'mp_correction' => 11,
            ],
            [
                'name' => 'ブラックスミス',
                'strength_correction' => 1,
                'dexterity_correction' => 1,
                'agility_correction' => 0,
                'intelligence_correction' => 1,
                'sense_correction' => 0,
                'mental_correction' => 0,
                'luck_correction' => 0,
                'hp_correction' => 12,
                'mp_correction' => 11,
            ],
            [
                'name' => 'エクセレント',
                'strength_correction' => 0,
                'dexterity_correction' => 1,
                'agility_correction' => 0,
                'intelligence_correction' => 0,
                'sense_correction' => 0,
                'mental_correction' => 1,
                'luck_correction' => 1,
                'hp_correction' => 12,
                'mp_correction' => 11,
            ],
            [
                'name' => 'サイバーオーガン',
                'strength_correction' => 1,
                'dexterity_correction' => 0,
                'agility_correction' => 1,
                'intelligence_correction' => 0,
                'sense_correction' => 1,
                'mental_correction' => 0,
                'luck_correction' => 0,
                'hp_correction' => 14,
                'mp_correction' => 9,
            ],
            [
                'name' => 'ハッカー',
                'strength_correction' => 0,
                'dexterity_correction' => 0,
                'agility_correction' => 0,
                'intelligence_correction' => 1,
                'sense_correction' => 1,
                'mental_correction' => 0,
                'luck_correction' => 1,
                'hp_correction' => 9,
                'mp_correction' => 14,
            ],
        ]);
    }
}